#!/bin/bash
#
#Echo lines in filename
#

if [ $# -ne 3 ]; then
	echo "Usage: line1 line_num filename"
	exit 1
else 
	if [ -e $3 ]; then
		tail -n +$1 $3 | head -n$2
#	export _POSIX2_VERSION=199209
#	tail +$1 $3 | head -n$2
	else
		echo "Open $3 error."
	fi
fi
