#!/bin/bash
#
#Math operate about command argument
#

if [ $# -ne 3 ]; then
	echo "Error: argument error"
	echo "Usage: $0 number1 op(+,-,x, /,%) number2"
	exit 1;
else
	case $2 in
		+)con=`expr $1 + $3`;;
		-)con=`expr $1 - $3`;;
		x)con=`expr $1 \* $3`;;
		/)con=`expr $1 / $3`;;
		%)con=`expr $1 % $3`;;
		*)echo "operator should be +,-,x,/,%"
			exit 1;;
		esac		
	echo "$1 $2 $3 = $con"
fi

