#!/bin/bash
#
#Max of three number
#

if [ $# -ne 3 ]; then
	echo "Error: three number needed"
	echo "Usage: $0 number1 number2 number3"
	echo "Function: find the max number in three"
	exit 1
else
	if [ $1 -gt $2 ]; then
		tmp=$1
	else 
		tmp=$2
	fi

	if [ $tmp -gt $3 ]; then
		tmp=$tmp
	else 
		tmp=$3
	fi

	echo "$tmp is Max in $@"
fi
