#!/bin/bash
#
#Reverse number
#
if [ $# -ne 1 ]; then
	echo "Error:argument error."
	echo "Usage:%0 number"
	echo "Function:Reverse number"
	exit 1
fi


number=$1
output_number=0
reg=0
while [ $number -gt 0 ]; do
	reg=`expr $number % 10`
	output_number=`expr $output_number \* 10 + $reg`
	number=`expr $number / 10`
done
	echo "$output_number"


